apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-1
spec:
  parallelism: 1
  template:
    metadata:
      name: job-wq-1
    spec:
      containers:
      - name: job
        image: busybox
        command:  ["sh", "-c", "while true ; do  date && sleep 3 ; done "]
      restartPolicy: Never
