apiVersion: v1
kind: Pod
metadata:
 labels:
   app: secretpod
 name: nginx-from-env-variable
spec:
  containers:
  - name: nginxsecretcontainer
    image: nginx
    env:
    - name: secret_username
      valueFrom:
       secretKeyRef:
        name: mysecret
        key: username.txt
    - name: secret_password
      valueFrom:
       secretKeyRef:
        name: mysecret
        key: password.txt

