apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  labels:
    app: nginx-500
  name: nginx-500
spec:
  replicas: 3
  selector:
      matchLabels:
        app: nginx-500
  template:
    metadata:
      labels:
        app: nginx-500
    spec:
      containers:
      - image: nginx
        name: nginx
