apiVersion: v1
kind: Pod
metadata:
  labels:
    running: afterLabels
  name: alpine
spec:
    containers:
    - image: alpine
      name: alpine
      command:
       - sleep
       - "60"
    restartPolicy: Always
