apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ank-daemon
  labels:
    daemon: "yup"
spec:
  selector:
    matchLabels:
      daemon: "pod"
  template:
    metadata:
      labels:
        daemon: pod
    spec:
      tolerations:
      - key: node-role.kubernetes.io
        operator: Equal
        value: master
        effect: NoSchedule
      containers:
      - name: ank-daemon-jr
        image: nginx
