apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
  name: busybox
spec:
      containers:
      - image: busybox
        name: busybox
        command:
          ["sleep", "15"]
      restartPolicy: Never
      nodeSelector:
         disktype: ssd
