apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-200
  name: nginx-deployment
spec:
  replicas: 2
  selector:
   matchLabels:
     app: nginx-200-pods-label
  template:
    metadata:
      labels:
        app: nginx-200-pods-label
    spec:
      containers:
      - image: nginx
        name: nginx-200-pod
        ports:
        - containerPort: 80
