 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: mongodb-pv-1
 spec:
   storageClassName: local-storage
   capacity:
     storage: 200Gi
   accessModes:
     - ReadWriteOnce
   hostPath:
     path: "/mnt/data"
