apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-200
  name: web-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx-200-pods-label
  type: NodePort
status:
  loadBalancer: {}
